import CommerceOperations from './CommerceOperations';
import { useEffect, useRef, useState } from 'react';
import { formatMoney } from '../../utils/money';
import CommerceActivation from './CommerceActivation';

type Channel={id:string;displayPhone:string|null;active:boolean;commerceEnabled:boolean;commercePolicyVersion:number;commercePolicy:Policy|null};
type Policy={eligibleProductIds:string[];autoQuote:boolean;ttlHours:number;maxTotal:string;maxLines:number;eligibilityAttested:boolean};
type Conversation={id:string;channelId:string;waId:string;status:string;version:number;assignedUserId:string|null;optedOutAt:string|null;lastInboundAt:string;updatedAt:string};
type Message={id:string;body:string;status:string;errorCode?:string|null;createdAt?:string;eventAt?:string};
type Draft={id:string;version:number;status:string;items:unknown;snapshot:unknown;reviewHash:string|null;quotationId:string|null};
type Attempt={id:string;outboxId:string;claimedAt:string;invokedAt:string|null;settledAt:string|null;status:string;providerMessageId:string|null;errorCode:string|null};
type Detail={conversation:Conversation;inbox:Message[];outbox:Message[];drafts:Draft[];attempts?:Attempt[]};
type Product={id:string;name:string;sku:string;unit:string;price:number;stock:number};
type Review={draftId:string;version:number;reviewHash:string;snapshot:unknown;text:string};
const emptyPolicy:Policy={eligibleProductIds:[],autoQuote:false,ttlHours:24,maxTotal:'5000',maxLines:5,eligibilityAttested:false};

function itemInputs(value:unknown):{productId:string;quantity:string;presentation?:'BASE'}[]{
  if(!Array.isArray(value))return [];
  return value.flatMap(item=>item&&typeof item==='object'&&typeof item.productId==='string'&&typeof item.quantity==='string'?[{productId:item.productId,quantity:item.quantity,presentation:'BASE' as const}]:[]);
}
function statusLabel(status:string){return ({PENDING:'Pendiente de envío',SENDING:'Enviando',SENT:'Aceptado por Meta',DELIVERED:'Entregado',READ:'Leído',UNKNOWN:'Entrega incierta',FAILED:'Falló',CANCELLED:'Cancelado antes de enviar',DRAFT:'Borrador',PENDING_REVIEW:'Pendiente de revisión',REVIEWED:'Revisado',ISSUED:'Proforma emitida'} as Record<string,string>)[status]??status;}

export default function CommerceInbox(){
  const [channels,setChannels]=useState<Channel[]>([]),[channelId,setChannelId]=useState(''),[conversations,setConversations]=useState<Conversation[]>([]);
  const [selectedId,setSelectedId]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[products,setProducts]=useState<Product[]>([]);
  const [policy,setPolicy]=useState<Policy>(emptyPolicy),[reply,setReply]=useState(''),[review,setReview]=useState<Review|null>(null);
  const [draftEdits,setDraftEdits]=useState<Record<string,{productId:string;quantity:string;presentation?:'BASE'}[]>>({});
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const lock=useRef(false),replyKey=useRef<string|null>(null),lastChannelId=useRef('');
  const selection=useRef({channelId,selectedId}),detailRequest=useRef(0),conversationRequest=useRef(0),productRequest=useRef(0);
  selection.current={channelId,selectedId};
  let ownRole='',ownUserId='';
  try {const user=JSON.parse(localStorage.getItem('nortex_user')??'{}');ownRole=typeof user.role==='string'?user.role:'';ownUserId=typeof user.id==='string'?user.id:'';} catch { /* permisos se verifican en el servidor */ }
  const canConfigure=['OWNER','ADMIN'].includes(ownRole);
  async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{
    const token=localStorage.getItem('nortex_token');
    const result=await fetch(`/api/whatsapp-commerce${path}`,{method,headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
    const payload=await result.json().catch(()=>({}));
    if(!result.ok)throw new Error(typeof payload.error==='string'?payload.error:'No se pudo comprobar el estado.');
    return payload as T;
  }
  async function loadChannels(){const data=await api<{items:Channel[]}>('/channels');setChannels(data.items);setChannelId(current=>current&&data.items.some(c=>c.id===current)?current:data.items[0]?.id??'');}
  async function loadConversations(id:string){const request=++conversationRequest.current;const data=await api<{items:Conversation[]}>(`/conversations?channelId=${encodeURIComponent(id)}`);if(request===conversationRequest.current&&selection.current.channelId===id)setConversations(data.items);}
  async function loadDetail(id:string){const request=++detailRequest.current,channel=selection.current.channelId;const data=await api<Detail>(`/conversations/${encodeURIComponent(id)}`);if(request===detailRequest.current&&selection.current.selectedId===id&&selection.current.channelId===channel&&data.conversation.channelId===channel)setDetail(data);}
  useEffect(()=>{let live=true;void loadChannels().catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false};},[]);
  useEffect(()=>{if(!channelId){setConversations([]);return}const channel=channels.find(c=>c.id===channelId);setPolicy(channel?.commercePolicy??emptyPolicy);
    if(lastChannelId.current!==channelId){lastChannelId.current=channelId;setSelectedId('');setDetail(null);setReview(null);setReply('');replyKey.current=null;setDraftEdits({});setProducts([]);setConversations([]);}
    let live=true;const request=++productRequest.current;
    void loadConversations(channelId).catch(e=>{if(live)setError(e.message)});if(canConfigure)void api<{items:Product[]}>(`/channels/${encodeURIComponent(channelId)}/products`).then(data=>{if(live&&request===productRequest.current&&selection.current.channelId===channelId)setProducts(data.items)}).catch(e=>{if(live)setError(e.message)});
    return()=>{live=false};
  },[channelId,channels,canConfigure]);
  useEffect(()=>{setDetail(null);setReview(null);setReply('');replyKey.current=null;setDraftEdits({});if(!selectedId)return;let live=true;void loadDetail(selectedId).catch(e=>{if(live)setError(e.message)});return()=>{live=false};},[selectedId,channelId]);
  async function act(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await action()}catch(e){setError(e instanceof Error?e.message:'No se pudo completar la acción.')}finally{lock.current=false;setBusy(false)}}
  const selected=channels.find(c=>c.id===channelId);
  const current=detail?.conversation.id===selectedId&&detail.conversation.channelId===channelId?detail.conversation:null;
  const timeline=[...(current?detail?.inbox??[]:[]).map(message=>({message,direction:'Cliente',at:message.eventAt??message.createdAt??''})),...(current?detail?.outbox??[]:[]).map(message=>({message,direction:'Tienda',at:message.createdAt??''}))].sort((a,b)=>a.at.localeCompare(b.at));
  const refresh=()=>void act(async()=>{await loadChannels();if(channelId)await loadConversations(channelId);if(selectedId)await loadDetail(selectedId);setNotice('Estado actualizado.');});
  const sendReply=()=>void act(async()=>{if(!current||!reply.trim())return;replyKey.current??=crypto.randomUUID();const result=await api<{outboxId:string;status:string}>(`/conversations/${current.id}/reply`,'POST',{version:current.version,body:reply.trim(),idempotencyKey:replyKey.current});setReply('');replyKey.current=null;await loadDetail(current.id);setNotice(`Respuesta ${statusLabel(result.status).toLowerCase()}. Consultá el estado de entrega.`);});
  return <section className="nx-shell-control rounded-card border p-4 space-y-4" aria-label="WhatsApp comercial">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="nx-shell-text text-lg font-semibold">WhatsApp comercial</h2><p className="nx-shell-muted text-sm">Conversaciones y proformas del negocio. La entrega se comprueba por separado.</p></div><button type="button" className="nx-shell-control rounded-control border px-3 py-2" disabled={busy} onClick={refresh}>Actualizar</button></header>
    {loading&&<p role="status">Cargando canales…</p>}{error&&<p role="alert" className="nx-tone-warning rounded-control border p-3 text-sm">{error}</p>}{notice&&<p role="status" className="nx-tone-success rounded-control border p-3 text-sm">{notice}</p>}
    {!loading&&!error&&channels.length===0&&<CommerceActivation canRequest={canConfigure}/>}
    {channels.length>0&&<><CommerceOperations/><label className="nx-shell-text block text-sm">Canal <select aria-label="Canal WhatsApp" className="nx-shell-control ml-2 rounded-control border px-3 py-2" value={channelId} onChange={e=>setChannelId(e.target.value)}>{channels.map(c=><option key={c.id} value={c.id}>{c.displayPhone??`Canal ${c.id.slice(-6)}`} · {c.commerceEnabled?'Activo':'Pausado'}</option>)}</select></label>
      {selected&&!selected.commerceEnabled&&<p className="nx-tone-warning rounded-control border p-3 text-sm">El canal comercial está pausado. Revisá la política antes de activarlo.</p>}
      {canConfigure&&selected&&<details className="nx-shell-control rounded-control border p-3"><summary className="nx-shell-text cursor-pointer font-medium">Política del canal</summary><div className="mt-3 grid gap-3 text-sm sm:grid-cols-2">
        <label>Productos elegibles<select aria-label="Productos elegibles" multiple className="nx-shell-control block min-h-32 w-full rounded-control border p-2" value={policy.eligibleProductIds} onChange={e=>setPolicy({...policy,eligibleProductIds:Array.from(e.currentTarget.selectedOptions,(option:HTMLOptionElement)=>option.value)})}>{products.map(p=><option value={p.id} key={p.id}>{p.name} · {p.sku} · {formatMoney(p.price)} · {p.stock} {p.unit}</option>)}</select></label>
        <div className="space-y-2"><label className="block">Vigencia en horas<input aria-label="Vigencia en horas" type="number" min="1" max="168" className="nx-shell-control ml-2 w-20 rounded-control border p-2" value={policy.ttlHours} onChange={e=>setPolicy({...policy,ttlHours:Number(e.target.value)})}/></label><label className="block">Total máximo en córdobas<input aria-label="Total máximo" className="nx-shell-control ml-2 w-28 rounded-control border p-2" value={policy.maxTotal} onChange={e=>setPolicy({...policy,maxTotal:e.target.value})}/></label><label className="block">Líneas máximas<input aria-label="Líneas máximas" type="number" min="1" max="20" className="nx-shell-control ml-2 w-20 rounded-control border p-2" value={policy.maxLines} onChange={e=>setPolicy({...policy,maxLines:Number(e.target.value)})}/></label></div>
        <label className="flex items-center gap-2"><input type="checkbox" checked={policy.autoQuote} onChange={e=>setPolicy({...policy,autoQuote:e.target.checked})}/>Permitir proforma automática dentro de límites</label>
        <label className="flex items-center gap-2"><input type="checkbox" checked={policy.eligibilityAttested} onChange={e=>setPolicy({...policy,eligibilityAttested:e.target.checked})}/>Confirmo que revisé la elegibilidad de estos productos y del canal</label>
      </div><div className="mt-3 flex gap-2"><button type="button" disabled={busy} className="nx-shell-control rounded-control border px-3 py-2" onClick={()=>void act(async()=>{await api(`/channels/${selected.id}/policy`,'PUT',{expectedVersion:selected.commercePolicyVersion,enabled:false,policy});await loadChannels();setNotice('Política guardada con el canal pausado.')})}>Guardar pausado</button><button type="button" disabled={busy||!policy.eligibilityAttested||policy.eligibleProductIds.length===0} className="nx-shell-control rounded-control border px-3 py-2" onClick={()=>void act(async()=>{await api(`/channels/${selected.id}/policy`,'PUT',{expectedVersion:selected.commercePolicyVersion,enabled:true,policy});await loadChannels();setNotice('Configuración guardada. Verificá el estado del canal y del proveedor antes del piloto.')})}>Activar canal</button></div></details>}
      <div className="grid gap-4 lg:grid-cols-[minmax(14rem,1fr)_minmax(0,2fr)]"><div className="nx-shell-control rounded-control border p-3"><h3 className="nx-shell-text mb-2 font-medium">Conversaciones</h3><div className="space-y-2">{conversations.length===0?<p className="nx-shell-muted text-sm">No hay conversaciones en este canal.</p>:conversations.map(c=><button type="button" key={c.id} onClick={()=>setSelectedId(c.id)} className="nx-shell-control block w-full rounded-control border p-3 text-left text-sm" aria-pressed={selectedId===c.id}><span className="nx-shell-text font-medium">{c.waId}</span><span className="nx-shell-muted ml-2">{c.status}{c.optedOutAt?' · no recibir mensajes':''}</span></button>)}</div></div>
      <div className="nx-shell-control rounded-control border p-3">{!current?<p className="nx-shell-muted">Seleccioná una conversación.</p>:<div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="nx-shell-text font-medium">{current.waId} · {current.status}</h3><div className="flex gap-2">{current.status!=='CLOSED'&&current.assignedUserId===null&&<button type="button" disabled={busy} className="nx-shell-control rounded-control border px-3 py-2" onClick={()=>void act(async()=>{await api(`/conversations/${current.id}/claim`,'POST',{version:current.version});await loadDetail(current.id);await loadConversations(channelId)})}>Tomar</button>}{current.status==='HUMAN'&&current.assignedUserId&&<button type="button" disabled={busy} className="nx-shell-control rounded-control border px-3 py-2" onClick={()=>void act(async()=>{await api(`/conversations/${current.id}/release`,'POST',{version:current.version});await loadDetail(current.id);await loadConversations(channelId)})}>Liberar</button>}</div></div>
        {current.optedOutAt&&<p className="nx-tone-warning text-sm">Este comprador pidió no recibir mensajes.</p>}
        <div className="max-h-80 space-y-2 overflow-auto" aria-label="Mensajes">{timeline.map(({message,direction})=><div key={`${direction}-${message.id}`} className="nx-shell-control rounded-control border p-2 text-sm"><b>{direction}</b> · {statusLabel(message.status)}<p className="whitespace-pre-wrap">{message.body}</p>{message.errorCode&&<p className="nx-tone-warning">Error: {message.errorCode}</p>}</div>)}</div>
        {current.status==='HUMAN'&&!current.optedOutAt&&current.assignedUserId===ownUserId&&<div><label className="nx-shell-text block text-sm">Respuesta humana<textarea aria-label="Respuesta humana" className="nx-shell-control mt-1 block w-full rounded-control border p-2" value={reply} onChange={e=>{setReply(e.target.value);replyKey.current=null}}/></label><button type="button" disabled={busy||!reply.trim()} className="nx-shell-control mt-2 rounded-control border px-3 py-2" onClick={sendReply}>Encolar respuesta</button></div>}
        {(detail?.attempts?.length??0)>0&&<details className="nx-shell-control rounded-control border p-3 text-sm"><summary className="nx-shell-text cursor-pointer">Comprobantes de envío</summary>{detail?.attempts?.map(a=><div key={a.id} className="nx-shell-control mt-2 rounded-control border p-2"><p>{({CLAIMED:'Preparado',SENDING:'Enviando',ACCEPTED:'Aceptado por Meta',UNKNOWN:'Resultado incierto',CANCELLED:'Cancelado antes de enviar'} as Record<string,string>)[a.status]??'Sin comprobar'} · {new Date(a.claimedAt).toLocaleString('es-NI')}</p>{a.providerMessageId&&<p className="break-all">Referencia Meta: {a.providerMessageId}</p>}{a.status==='UNKNOWN'&&<p className="nx-tone-warning">La referencia no confirma entrega. Conservá este comprobante para revisión.</p>}</div>)}</details>}
        <div className="space-y-3"><h4 className="nx-shell-text font-medium">Proformas</h4>{detail?.drafts.length===0&&<p className="nx-shell-muted text-sm">No hay borradores.</p>}{detail?.drafts.map(d=>{const edits=draftEdits[d.id]??itemInputs(d.items),editable=d.status!=='ISSUED';return <div key={d.id} className="nx-shell-control rounded-control border p-3 text-sm"><div className="flex justify-between gap-2"><b>{d.id.slice(-8)} · {statusLabel(d.status)}</b><span>Versión {d.version}</span></div>{d.quotationId&&<p>Proforma #{d.quotationId}</p>}{edits.map((item,index)=><div key={`${d.id}-${index}`} className="mt-2 flex flex-wrap gap-2"><select aria-label={`Producto línea ${index+1}`} disabled={!editable} className="nx-shell-control rounded-control border p-2" value={item.productId} onChange={e=>setDraftEdits({...draftEdits,[d.id]:edits.map((x,i)=>i===index?{...x,productId:e.target.value}:x)})}>{products.find(p=>p.id===item.productId)?null:<option value={item.productId}>{item.productId}</option>}{products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input aria-label={`Cantidad línea ${index+1}`} disabled={!editable} className="nx-shell-control w-24 rounded-control border p-2" value={item.quantity} onChange={e=>setDraftEdits({...draftEdits,[d.id]:edits.map((x,i)=>i===index?{...x,quantity:e.target.value}:x)})}/></div>)}
          {['DRAFT','PENDING_REVIEW','REVIEWED'].includes(d.status)&&<div className="mt-3 flex flex-wrap gap-2">{draftEdits[d.id]&&<button disabled={busy} className="nx-shell-control rounded-control border px-3 py-2" onClick={()=>void act(async()=>{await api(`/drafts/${d.id}/update`,'POST',{version:d.version,items:edits});await loadDetail(current.id);setReview(null);setNotice('Borrador corregido. Revisalo otra vez.')})}>Guardar correcciones</button>}<button disabled={busy} className="nx-shell-control rounded-control border px-3 py-2" onClick={()=>void act(async()=>{const value=await api<Review>(`/drafts/${d.id}/review`,'POST',{version:d.version});setReview(value);await loadDetail(current.id);setNotice('Revisión calculada. Comprobá productos, cantidades y total antes de emitir.')})}>Revisar proforma</button></div>}
          {review?.draftId===d.id&&<div className="nx-tone-warning mt-3 rounded-control border p-3"><p className="whitespace-pre-wrap">{review.text}</p><button disabled={busy} className="nx-shell-control mt-2 rounded-control border px-3 py-2" onClick={()=>void act(async()=>{try{const result=await api<{quotationId:string;outboxId:string}>(`/drafts/${d.id}/issue`,'POST',{version:review.version,reviewHash:review.reviewHash});setReview(null);await loadDetail(current.id);setNotice(`Proforma ${result.quotationId} emitida. Mensaje encolado; comprobá su entrega.`)}catch(error){setReview(null);await loadDetail(current.id);throw error}})}>Emitir proforma revisada</button></div>}
        </div>})}</div>
      </div>}</div></div>
    </>}
  </section>;
}
