import React, { useEffect, useLayoutEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import FluidSheet from '../ui/FluidSheet';
import type { PromotionOperationResponse } from '../../shared/promotions';
import type { PromotionCheckoutController } from '../../hooks/usePromotionCheckout';
import { formatMoney } from '../../utils/money';
import { assistantButtonClass } from '../assistant/AssistantCatalogSelect';
export function PromotionCheckoutSheet({ controller, onContinue, onRecovered }: { controller: PromotionCheckoutController; onContinue: (method: string) => void; onRecovered: (sale: NonNullable<PromotionOperationResponse['sale']>) => void }) {
    const [resumeMethod, setResumeMethod] = useState<string | null>(null);
    useEffect(() => { if (resumeMethod) { setResumeMethod(null); onContinue(resumeMethod); } }, [resumeMethod, onContinue]);
    const { attempt, open, busy, error } = controller; const quote = attempt?.quote;
    useLayoutEffect(() => { if (!open) return; const background = document.getElementById('root'); if (!background) return; const wasInert = background.hasAttribute('inert'); background.setAttribute('inert', ''); return () => { if (!wasInert) background.removeAttribute('inert'); }; }, [open]);
    return createPortal(<FluidSheet open={open} onClose={controller.close} ariaLabel="Revisar precio antes de cobrar" className="nx-app-shell" size="full" panelClassName="max-w-xl" dragToDismiss={false}><section data-operational-alerts="" className="min-h-0 space-y-4 overflow-y-auto p-4 sm:p-5">
        <h2 className="nx-shell-text text-lg font-bold">{attempt?.sent ? 'Comprobar la venta' : 'Revisá el precio antes de cobrar'}</h2>
        {error && <p role="alert" className="nx-tone-warning rounded-control border p-3 text-sm">{error}</p>}
        {quote && <>{quote.warnings?.map((warning, index) => <p key={index} className="nx-tone-warning rounded-control border p-3 text-sm">{warning}</p>)}<p className="nx-shell-muted text-sm">{quote.hasPromotions ? 'El negocio tiene promociones aplicables a este carrito.' : 'Comprobamos el precio actual de este carrito.'}</p><ul className="space-y-3">{quote.lines.map((line, index) => <li key={index} className="nx-shell-border space-y-1 border-t pt-2"><p className="nx-shell-text text-sm font-semibold">{line.name}</p><p className="nx-shell-muted text-sm">{line.quantity} {line.unit} · Precio unitario {formatMoney(line.unitPrice)} · Total de línea {formatMoney(line.lineTotal)}</p>{line.promotion && <p className="nx-tone-positive text-sm">{line.promotion.name} · {line.promotion.percent}% de descuento</p>}</li>)}</ul><dl className="nx-shell-border space-y-2 border-t pt-3"><div><dt className="nx-shell-muted text-sm">Total a cobrar</dt><dd className="nx-shell-text text-2xl font-bold">{formatMoney(quote.total)}</dd></div><div><dt className="nx-shell-muted text-xs">IVA incluido</dt><dd className="nx-shell-text text-sm">{formatMoney(quote.vatAmount)}</dd></div></dl></>}
        {attempt?.recovered ? <><p role="status" className="nx-tone-positive text-sm">Venta confirmada. Total registrado: {formatMoney(attempt.recovered.total)}</p><p className="nx-shell-muted break-all text-xs">Comprobante: {attempt.recovered.id}</p><button type="button" className={assistantButtonClass} onClick={() => onRecovered(attempt.recovered as NonNullable<PromotionOperationResponse['sale']>)}>Ver comprobante de la venta</button></> : attempt?.sent ? <><p className="nx-shell-muted text-sm">El carrito y esta referencia permanecen protegidos. Una respuesta perdida no permite volver a cobrar.</p><p className="nx-shell-muted break-all text-xs">Referencia de venta: {attempt.payload.offlineId}</p><button type="button" className={assistantButtonClass} disabled={busy} onClick={() => { void controller.recover(); }}>Comprobar venta registrada</button><button type="button" className={assistantButtonClass} disabled={busy} onClick={() => void controller.cancelAttempt()}>Cancelar intento y revisar carrito</button><p className="nx-shell-muted text-xs">Primero se comprobará si la venta ya existe. El carrito sólo se libera cuando el servidor invalida este intento y sus revisiones anteriores.</p></> : <div className="flex flex-wrap gap-2"><button type="button" disabled={busy} className={assistantButtonClass} onClick={controller.close}>Volver al carrito</button>{quote && <button type="button" disabled={busy} className={`${assistantButtonClass} nx-tone-positive`} onClick={() => { controller.accept(); setResumeMethod(attempt.payload.paymentMethod); }}>Aceptar total y continuar al cobro</button>}</div>}
    </section></FluidSheet>, document.body);
}
