import React from 'react';
import type { AssistantOperationsController } from '../../hooks/useAssistantOperations';
import type { AssistantCapabilities } from '../../shared/assistant';
import type { AssistantJson, AssistantJsonObject } from '../../shared/assistantOperations';
import type { AssistantRequest } from '../../hooks/useNortexAssistant';
import { AssistantPromotionDraft } from './AssistantPromotionDraft';
import { AssistantActionSources } from './AssistantActionSources';
import { AssistantCatalogSelect, assistantButtonClass, assistantInputClass } from './AssistantCatalogSelect';
const text = (value: AssistantJson | undefined) => typeof value === 'string' ? value : '';
const objects = (value: AssistantJson | undefined): AssistantJsonObject[] => Array.isArray(value) ? value.filter((item): item is AssistantJsonObject => !!item && typeof item === 'object' && !Array.isArray(item)) : [];
const lineLabels: Record<string, string> = { name: 'Producto', productName: 'Producto', quantity: 'Cantidad', unit: 'Unidad', unitAtOrder: 'Unidad base de la orden', batchNumber: 'Lote', warehouseName: 'Bodega', warehouse: 'Bodega', unitCost: 'Costo unitario', expiryDate: 'Vencimiento', lineTotal: 'Total', baseQuantity: 'Cantidad base', supplierName: 'Proveedor', invoiceNumber: 'Factura', source: 'Procedencia', value: 'Valor', before: 'Antes', after: 'Después', price: 'Precio', originalPrice: 'Precio habitual', promotionalPrice: 'Precio con promoción', discountPercent: 'Descuento %', quantityBase: 'Cantidad base', batchStockBefore: 'Existencias actuales del lote', warehouseStockBefore: 'Existencias actuales en bodega', productNameAtOrder: 'Producto', quantityOrdered: 'Cantidad solicitada', estimatedTotal: 'Total estimado', packSize: 'Unidades por empaque', wholesaleMinQty: 'Cantidad mínima de mayoreo', startsAt: 'Comienza', endsAt: 'Termina' };
const titles = { PURCHASE_ORDER_DRAFT: 'Orden de compra en borrador', BATCH_WRITEOFF: 'Retiro de un lote', SUPPLIER_RETURN: 'Devolución al proveedor', PROMOTION: 'Promoción de productos' };
const previewValue = (key: string, value: unknown) => ['startsAt', 'endsAt'].includes(key) && typeof value === 'string' && Number.isFinite(new Date(value).getTime()) ? `${new Intl.DateTimeFormat('es-NI', { timeZone: 'America/Managua', dateStyle: 'short', timeStyle: 'short', hour12: false }).format(new Date(value))} · Managua` : String(value);
export function AssistantActionReview({ controller, capabilities, request }: { controller: AssistantOperationsController; capabilities: AssistantCapabilities; request: AssistantRequest }) {
    const { proposal, draft, dirty, uncertain, busy } = controller; if (!proposal || !draft) return null;
    const final = !!proposal.result || ['COMMITTED', 'CANCELLED', 'EXPIRED'].includes(proposal.status);
    const disabled = busy || uncertain || final || !capabilities.actionPrepare;
    const change = (key: string, value: AssistantJson) => controller.edit({ ...draft, ...(proposal.kind === 'BATCH_WRITEOFF' && key !== 'physicalRemovalConfirmed' ? { physicalRemovalConfirmed: false } : {}), ...(proposal.kind === 'SUPPLIER_RETURN' && key !== 'physicalShipmentConfirmed' ? { physicalShipmentConfirmed: false } : {}), [key]: value });
    const field = (key: string, label: string, type = 'text') => <label className="nx-shell-text block min-w-0 text-sm">{label}<input type={type} className={assistantInputClass} value={text(draft[key])} onChange={event => change(key, event.target.value)} disabled={disabled} /></label>;
    const catalog = (key: string, label: string, kind: 'products' | 'suppliers' | 'warehouses') => <AssistantCatalogSelect label={label} kind={kind} value={text(draft[key])} request={request} disabled={disabled} onChange={id => change(key, id ?? '')} />;
    return <section aria-label="Revisión de acción" className="nx-shell-control space-y-4 rounded-card border p-4">
        <h3 className="nx-shell-text font-bold">{titles[proposal.kind]}</h3>
        <p className="nx-shell-muted break-all text-xs">Referencia: {proposal.id} · Revisión {proposal.version}</p>
        {proposal.result ? <div role="status" className="nx-tone-positive space-y-2 rounded-control border p-3"><p>{proposal.result.message}</p><p className="break-all text-xs">Comprobante: {proposal.result.id}</p></div> : <>
            {!capabilities.actionPrepare && <p className="nx-tone-warning text-sm">Tu acceso actual permite consultar esta propuesta. La preparación está desactivada.</p>}
            <fieldset disabled={disabled} className="min-w-0 space-y-3">
                {proposal.kind === 'PURCHASE_ORDER_DRAFT' && <>{catalog('supplierId', 'Proveedor', 'suppliers')}{field('expectedDate', 'Fecha esperada', 'date')}{field('notes', 'Notas')}<p className="nx-shell-muted text-xs">Las cantidades usan la unidad base del catálogo. Se guardará una orden en borrador; no ingresará mercadería ni registrará deuda.</p>
                    {objects(draft.items).map((line, index) => <div key={index} className="nx-shell-border space-y-2 border-t pt-3"><AssistantCatalogSelect label={`Producto ${index + 1}`} kind="products" value={text(line.productId)} request={request} disabled={disabled} onChange={id => change('items', objects(draft.items).map((item, row) => row === index ? { ...item, productId: id ?? '' } : item))} /><div className="grid grid-cols-2 gap-2">{[['quantity', 'Cantidad base'], ['unitCost', 'Costo unitario C$']].map(([key, label]) => <label key={key} className="nx-shell-text min-w-0 text-sm">{label}<input inputMode="decimal" className={assistantInputClass} value={text(line[key])} onChange={event => change('items', objects(draft.items).map((item, row) => row === index ? { ...item, [key]: event.target.value } : item))} /></label>)}</div></div>)}
                    <button type="button" className={assistantButtonClass} onClick={() => change('items', [...objects(draft.items), { productId: '', quantity: '', unitCost: '' }])}>Agregar producto</button></>}
                {proposal.kind === 'BATCH_WRITEOFF' && <><AssistantActionSources resetKey={proposal.id} kind={proposal.kind} draft={draft} request={request} disabled={disabled} onChange={controller.edit} productId={text(proposal.preview?.lines[0]?.productId)} />{catalog('warehouseId', 'Bodega', 'warehouses')}{field('quantity', 'Cantidad que se retira')}{field('reason', 'Motivo del retiro')}<label className="nx-shell-text flex min-h-tap items-center gap-2 text-sm"><input type="checkbox" checked={draft.physicalRemovalConfirmed === true} onChange={event => change('physicalRemovalConfirmed', event.target.checked)} />Confirmo que retiré físicamente esta cantidad del lote</label></>}
                {proposal.kind === 'SUPPLIER_RETURN' && <><AssistantActionSources resetKey={proposal.id} kind={proposal.kind} draft={draft} request={request} disabled={disabled} onChange={controller.edit} productId={text(proposal.preview?.lines[0]?.productId)} /><label className="nx-shell-text block text-sm">Motivo<select className={assistantInputClass} value={text(draft.reasonCode)} onChange={event => change('reasonCode', event.target.value)}><option value="">Seleccioná el motivo</option>{[['DAMAGE', 'Daño'], ['EXPIRED', 'Vencimiento'], ['QUALITY', 'Calidad'], ['WRONG_ITEM', 'Producto equivocado'], ['OVER_DELIVERY', 'Cantidad excedida'], ['OTHER', 'Otro']].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{field('reason', 'Detalle del motivo')}{field('supplierReference', 'Referencia del proveedor')}<p className="nx-shell-muted text-xs">La devolución usa la procedencia registrada de la mercadería. No genera una nota de crédito ni reduce la cuenta por pagar.</p><label className="nx-shell-text flex min-h-tap items-center gap-2 text-sm"><input type="checkbox" checked={draft.physicalShipmentConfirmed === true} onChange={event => change('physicalShipmentConfirmed', event.target.checked)} />Confirmo que despaché físicamente esta mercadería al proveedor</label></>}
                {proposal.kind === 'PROMOTION' && <AssistantPromotionDraft draft={draft} request={request} disabled={disabled} onChange={controller.edit} />}
            </fieldset>
            {dirty && <p role="status" className="nx-tone-warning text-sm">Hay cambios sin calcular. La revisión anterior ya no se puede confirmar.</p>}
            {!!proposal.issues.length && <ul className="nx-tone-warning list-disc space-y-1 pl-4 text-sm">{proposal.issues.map((issue, index) => <li key={index}>{issue}</li>)}</ul>}
            {proposal.preview && <section aria-label="Efectos de la acción" className="nx-shell-border space-y-3 border-t pt-3"><h4 className="nx-shell-text font-semibold">{proposal.preview.summary}</h4><dl className="space-y-2">{proposal.preview.effects.map((effect, index) => <div key={index}><dt className="nx-shell-muted text-sm">{effect.label}</dt><dd className="nx-shell-text font-semibold">{effect.value}{effect.unit ? ` ${effect.unit}` : ''}</dd></div>)}</dl>{proposal.preview.lines.map((line, index) => <dl key={index} className="nx-shell-border space-y-1 border-t pt-2 text-sm">{Object.entries(line).filter(([key, value]) => !!lineLabels[key] && (typeof value === 'string' || typeof value === 'number')).map(([key, value]) => <div key={key} className="flex flex-wrap gap-x-2"><dt className="nx-shell-muted">{lineLabels[key]}</dt><dd className="nx-shell-text break-words">{previewValue(key, value)}</dd></div>)}</dl>)}{proposal.preview.lines.map((line, index) => Array.isArray(line.prices) && <div key={`prices-${index}`} className="max-w-full overflow-x-auto"><table className="nx-shell-text w-full text-left text-sm"><thead><tr><th>Presentación</th><th>Precio normal C$</th><th>Precio promocional C$</th></tr></thead><tbody>{objects(line.prices).map((price, row) => <tr key={row}><td>{text(price.label)}</td><td>{text(price.before)}</td><td>{text(price.after)}</td></tr>)}</tbody></table></div>)}{proposal.preview.warnings.map((warning, index) => <p key={index} className="nx-tone-warning text-sm">{warning}</p>)}</section>}
            {uncertain ? <div className="space-y-2"><p role="status" className="nx-tone-warning text-sm">Estamos comprobando el resultado. La revisión y su referencia permanecen bloqueadas para evitar otra operación.</p><button type="button" className={assistantButtonClass} disabled={busy} onClick={() => void controller.recover()}>Comprobar resultado</button><button type="button" className={assistantButtonClass} disabled={busy || !capabilities.actionConfirm || !capabilities.executionEnabled} onClick={() => void controller.confirm()}>Reintentar la misma confirmación</button></div> : !final && <div className="flex flex-wrap gap-2"><button type="button" className={assistantButtonClass} disabled={disabled || (!dirty && proposal.status === 'READY')} onClick={() => void controller.preview()}>Guardar y calcular efectos</button><button type="button" className={`${assistantButtonClass} nx-tone-positive`} disabled={disabled || dirty || proposal.status !== 'READY' || !!proposal.issues.length || !proposal.preview || !capabilities.actionConfirm || !capabilities.executionEnabled} onClick={() => void controller.confirm()}>{proposal.preview?.confirmLabel ?? 'Confirmar acción revisada'}</button></div>}
            {(!capabilities.actionConfirm || !capabilities.executionEnabled) && <p className="nx-shell-muted text-sm">La ejecución está desactivada para tu acceso actual. Tus correcciones permanecen aquí.</p>}
        </>}
    </section>;
}
